export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const STORE_CONTAINER = 'STORE_CONTAINER';
export const STORE_CONTAINERS = 'STORE_CONTAINERS';
export const ADD_CONTAINER = 'ADD_CONTAINER';
export const LOAD_EVENTS = 'LOAD_EVENTS';
export const LOAD_PROJECT_SETTINGS = 'LOAD_PROJECT_SETTINGS';
